Add & Remove Functions
rebaz36/ToDoList-Webpack pull request #2
Opened 2022-09-30 21:02 UTC by rebaz36

[To Do list: add & remove](https://github.com/microverseinc/curriculum-javascript/blob/main/todo-list/m3_add_remove.md)

- Update index.html
- Update styles
- Add Js. for todo functionality

2022-09-30 21:46 UTC, Kamba56 requested changes
Hi @rebaz36, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- [x] All linters passed👏👏👏
- [ ] Great use of Github flow👏👏👏

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-30 21:46 UTC, Kamba56 commented on src/todolist.js
> +      id,
- [ ] Please asdemanded by the project requirements, the properties of each task should be `description`, `completed` and `index`. Kindly fix that please.

2022-09-30 21:46 UTC, Kamba56 commented on src/todolist.js
> +    const id = this.#toDo.length;
- [ ] I noticed that your index is the length of the array before the new task is pushed in so your index starts from zero. Please as demanded by project requirements, kindly make the property `index` set to the value of the new array length (i.e. if you're adding a 5th task to the list, the index of that task should equal to 5). You an achieve this by changing line `24` of your code to `const index = this.#toDo.length + 1;`

2022-09-30 21:46 UTC, Kamba56 commented on src/index.js
> +      modifyDescription(index, inputTask.value);
- [ ] Kindly create a new file in a `modules` folder and move your functions there, then import it to your index.js file as demanded by the second project requirement. This is also best ES6 practice.

2022-09-30 22:48 UTC, rebaz36 commented
Thanks for the tip @Kamba56

2022-09-30 23:23 UTC, mahbubul14 requested changes
Hi @rebaz36 ,

Great work on making the changes requested by the previous reviewer 👏

You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.

# Required Changes ♻️

- [ ] Kindly check the inline comments under the review. :arrow_down: 

###  To Highlights
:heavy_check_mark: No linter error.
:heavy_check_mark: Proper Github flow used.

### Optional suggestions

Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better.

- [ ]  Currently, your `README` file is not descriptive and professional enough. Please update your `README` file. You can use [this template ](https://github.com/microverseinc/readme-template)for the `README` but remember to customize it to your project.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification. You can also reach me on [slack](https://microverse-students.slack.com/team/U01J39GL614)

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-09-30 23:23 UTC, mahbubul14 commented on src/index.js
> +
- [ ] As the previous reviewer suggested:

> Kindly create a new file in a modules folder and move your functions there, then import it to your index.js file as demanded by the second project requirement. This is also the best ES6 practice.

- [ ] Please work on it. :+1:

2022-10-01 00:08 UTC, franclobo requested changes
Hi @rebaz36, 

# Required Changes ♻️

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights

- No linter errors ✔️ 
- Correct Github flow ✔️ 
- Professional README file ✔️ 
- Descriptive PR ✔️ 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
**_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._**

2022-10-01 00:08 UTC, franclobo commented on src/index.js
> +
- [ ] As the last code reviewer said 👀: **Kindly create a new file in a modules folder and move your functions there, then import it to your index.js file as demanded by the second project requirement. This is also the best ES6 practice.**

2022-10-01 10:43 UTC, fobadara approved these changes
Hi @rebaz36, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
✅ Linters are passing

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-01 12:35 UTC, merged